# Foundry configuration file

[default]
src = "./src"                 # Directory for source contracts
test = "./test"               # Directory for test contracts
out = "./out"                 # Directory for build artifacts
libs = ["./lib"]              # Directory for libraries and dependencies
solc_version = "0.8.20"       # Solidity compiler version

# Enable optimizer for Solidity compiler
[profile.default]
optimize = true               # Enable optimization
optimizer_runs = 200          # Number of optimization runs

# Gas report configuration (optional)
gas_reports = ["MyContract"]  # Specify contracts for which to generate gas reports

